name: Deploy Laravel to o2switch

on:
  push:
    branches:
      - main # Déclenche le workflow a chaque push sur la branche principale

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout du code
      uses: actions/checkout@v4

    - name: Configuration de la connexion SSH
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        known_hosts: ${{ secrets.SSH_HOST }}

    - name: Déploiement via SSH sur le serveur o2switch
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} '
          echo "Démarrage du déploiement..."
          # Navigue vers le chemin du dépôt Git sur le serveur o2switch
          cd /home/elha2196/repositories/bidaya2025

          # Met à jour le code depuis le dépôt GitHub
          echo "Mise à jour du dépôt Git..."
          git pull origin main

          # Installe les dépendances Composer en mode production
          echo "Exécution de Composer install..."
          composer install --no-dev --optimize-autoloader

          # Exécute les migrations de la base de données (si nécessaire)
          echo "Exécution des migrations de la base de données..."
          php artisan migrate --force

          # Nettoie et optimise les caches de Laravel
          echo "Nettoyage et rafraîchissement des caches..."
          php artisan cache:clear
          php artisan config:cache
          php artisan route:cache
          php artisan view:cache

          echo "Déploiement terminé avec succès !"
        '

    - name: Validation du déploiement
      run: |
        echo "Validation du déploiement en cours..."
        echo "Validation du déploiement réussie."