# .github/workflows/deploy.yml
name: Deploy O2Switch

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup PHP 8.3
      uses: shivammathur/setup-php@v2
      with:
        php-version: 8.3
        extensions: mbstring, xml, ctype, iconv, intl, pdo, pdo_mysql, dom, filter, gd, json

    - name: Install Composer dependencies
      run: composer install --no-dev --optimize-autoloader --no-interaction

    - name: Deploy to O2Switch
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        timeout: 60s
        script: |
          cd nataswim.fr
          
          # Backup current release
          if [ -d "current" ]; then
            mv current backup_$(date +%Y%m%d_%H%M%S)
          fi
          
          # Fresh deployment
          rm -rf temp_deploy
          git clone https://github.com/nataswim/bidaya2025.git temp_deploy
          cd temp_deploy
          
          # Install dependencies
          composer install --no-dev --optimize-autoloader --no-interaction
          
          # Configure .env for production
          cp .env.example .env
          sed -i "s|APP_ENV=.*|APP_ENV=production|" .env
          sed -i "s|APP_DEBUG=.*|APP_DEBUG=false|" .env
          sed -i "s|APP_URL=.*|APP_URL=https://nataswim.fr|" .env
          sed -i "s|APP_KEY=|APP_KEY=${{ secrets.APP_KEY }}|" .env
          sed -i "s|DB_DATABASE=elha2196_bidaya2025|DB_DATABASE=${{ secrets.DB_DATABASE }}|" .env
          sed -i "s|DB_USERNAME=elha2196_bidaya|DB_USERNAME=${{ secrets.DB_USERNAME }}|" .env  
          sed -i "s|DB_PASSWORD=|DB_PASSWORD=${{ secrets.DB_PASSWORD }}|" .env
          
          # Laravel setup
          chmod -R 775 storage bootstrap/cache
          php artisan migrate --force
          php artisan storage:link
          php artisan config:cache
          php artisan route:cache
          php artisan view:cache
          
          # Switch to new release (atomic deployment)
          cd ..
          mv temp_deploy current

    - name: Clean old releases  
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        script: |
          cd nataswim.fr
          # Keep only last 3 backups
          ls -t | grep "backup_" | tail -n +4 | xargs rm -rf 2>/dev/null || true