# .github/workflows/deploy.yml
name: Deploy to O2Switch

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup PHP 8.3
      uses: shivammathur/setup-php@v2
      with:
        php-version: 8.3
        extensions: mbstring, xml, ctype, iconv, intl, pdo, pdo_mysql, dom, filter, gd, json

    - name: Install Composer dependencies
      run: composer install --no-dev --optimize-autoloader --no-interaction

    - name: Create production .env
      run: |
        cp .env.example .env
        sed -i "s|APP_ENV=.*|APP_ENV=production|" .env
        sed -i "s|APP_DEBUG=.*|APP_DEBUG=false|" .env
        sed -i "s|APP_URL=.*|APP_URL=https://nataswim.fr|" .env
        sed -i "s|APP_KEY=|APP_KEY=${{ secrets.APP_KEY }}|" .env
        sed -i "s|DB_DATABASE=elha2196_bidaya2025|DB_DATABASE=${{ secrets.DB_DATABASE }}|" .env
        sed -i "s|DB_USERNAME=elha2196_bidaya|DB_USERNAME=${{ secrets.DB_USERNAME }}|" .env
        sed -i "s|DB_PASSWORD=|DB_PASSWORD=${{ secrets.DB_PASSWORD }}|" .env

    - name: Setup SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/deploy_key
        chmod 600 ~/.ssh/deploy_key
        ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

    - name: Deploy via rsync
      run: |
        rsync -avz --delete \
          --exclude='.git' \
          --exclude='node_modules' \
          --exclude='.github' \
          -e "ssh -i ~/.ssh/deploy_key -o StrictHostKeyChecking=no" \
          ./ ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }}:public_html/nataswim.fr/temp_deploy/

    - name: Finalize deployment
      run: |
        ssh -i ~/.ssh/deploy_key -o StrictHostKeyChecking=no ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} << 'EOF'
          cd public_html/nataswim.fr
          
          # Backup current
          if [ -d "current" ]; then
            mv current backup_$(date +%Y%m%d_%H%M%S)
          fi
          
          # Move temp to current
          mv temp_deploy current
          
          # Set permissions
          cd current
          chmod -R 775 storage bootstrap/cache
          
          # Laravel commands
          php artisan migrate --force
          php artisan config:cache
          php artisan route:cache
          php artisan view:cache
          
          # Web access
          cd ..
          rm -f index.php .htaccess
          ln -s current/public/index.php index.php
          ln -s current/public/.htaccess .htaccess
        EOF