# .github/workflows/deploy.yml
name: Deploy to O2Switch

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup PHP 8.3
      uses: shivammathur/setup-php@v2
      with:
        php-version: 8.3
        extensions: mbstring, xml, ctype, iconv, intl, pdo, pdo_mysql, dom, filter, gd, iconv, json, mbstring, pdo

    - name: Cache Composer dependencies
      uses: actions/cache@v3
      with:
        path: /tmp/composer-cache
        key: ${{ runner.os }}-${{ hashFiles('**/composer.lock') }}

    - name: Install Composer dependencies
      run: composer install --no-dev --optimize-autoloader --no-interaction

    - name: Create .env file
      run: |
        cp .env.example .env
        echo "APP_KEY=${{ secrets.APP_KEY }}" >> .env.tmp
        echo "DB_DATABASE=${{ secrets.DB_DATABASE }}" >> .env.tmp
        echo "DB_USERNAME=${{ secrets.DB_USERNAME }}" >> .env.tmp
        echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env.tmp
        
        # Remplacer les valeurs dans le fichier .env
        while IFS='=' read -r key value; do
          if grep -q "^${key}=" .env; then
            # Échapper les caractères spéciaux pour sed
            escaped_value=$(printf '%s\n' "$value" | sed 's/[[\.*^$(){}?+|/]/\\&/g')
            sed -i "s/^${key}=.*/${key}=${escaped_value}/" .env
          fi
        done < .env.tmp
        
        rm .env.tmp

    - name: Generate optimized files
      run: |
        php artisan config:cache
        php artisan route:cache
        php artisan view:cache

    - name: Deploy to O2Switch
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        script: |
          cd public_html/nataswim.fr
          
          # Créer structure de déploiement
          mkdir -p releases/$(date +%Y%m%d_%H%M%S)
          cd releases/$(date +%Y%m%d_%H%M%S)
          
          # Clone du repository
          git clone https://github.com/nataswim/bidaya2025.git .
          
          # Installation des dépendances
          composer install --no-dev --optimize-autoloader --no-interaction
          
          # Configuration Laravel avec les bonnes valeurs
          cp .env.example .env
          
          # Remplacer les valeurs sensibles dans .env
          sed -i "s|APP_KEY=|APP_KEY=${{ secrets.APP_KEY }}|" .env
          sed -i "s|DB_DATABASE=elha2196_bidaya2025|DB_DATABASE=${{ secrets.DB_DATABASE }}|" .env
          sed -i "s|DB_USERNAME=elha2196_bidaya|DB_USERNAME=${{ secrets.DB_USERNAME }}|" .env
          sed -i "s|DB_PASSWORD=|DB_PASSWORD=${{ secrets.DB_PASSWORD }}|" .env
          
          # Permissions Laravel
          chmod -R 775 storage bootstrap/cache
          
          # Migrations (si nécessaire)
          php artisan migrate --force
          
          # Optimisations
          php artisan config:cache
          php artisan route:cache
          php artisan view:cache
          
          # Mise à jour du symlink
          cd ../../
          rm -f current
          ln -s releases/$(date +%Y%m%d_%H%M%S) current
          
          # Configuration du document root vers current/public
          if [ ! -L index.php ]; then
            rm -f index.php 2>/dev/null || true
            ln -s current/public/index.php index.php
          fi

    - name: Clean old releases
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        script: |
          cd public_html/nataswim.fr/releases
          ls -t | tail -n +6 | xargs rm -rf 2>/dev/null || true