# .github/workflows/deploy.yml
name: Deploy to O2Switch

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup PHP 8.3
      uses: shivammathur/setup-php@v2
      with:
        php-version: 8.3
        extensions: mbstring, xml, ctype, iconv, intl, pdo, pdo_mysql, dom, filter, gd, json

    - name: Install Composer dependencies
      run: composer install --no-dev --optimize-autoloader --no-interaction

    - name: Deploy to O2Switch
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        script: |
          cd public_html/nataswim.fr
          
          # Backup si existe
          if [ -d "current" ]; then
            cp -r current backup_$(date +%Y%m%d_%H%M%S) 2>/dev/null || true
          fi
          
          # Nouveau déploiement
          rm -rf temp_deploy
          git clone https://github.com/nataswim/bidaya2025.git temp_deploy
          cd temp_deploy
          
          # Installation
          composer install --no-dev --optimize-autoloader --no-interaction
          
          # Configuration .env
          cp .env.example .env
          echo "APP_KEY=${{ secrets.APP_KEY }}" > .env.temp
          echo "DB_DATABASE=${{ secrets.DB_DATABASE }}" >> .env.temp
          echo "DB_USERNAME=${{ secrets.DB_USERNAME }}" >> .env.temp  
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env.temp
          
          # Merger les configurations
          cat .env.example > .env
          while IFS='=' read -r key value; do
            if [ ! -z "$value" ]; then
              grep -v "^$key=" .env > .env.new || true
              echo "$key=$value" >> .env.new
              mv .env.new .env
            fi
          done < .env.temp
          rm .env.temp
          
          # Permissions
          chmod -R 775 storage bootstrap/cache
          
          # Migrations
          php artisan migrate --force
          
          # Cache
          php artisan config:cache
          php artisan route:cache  
          php artisan view:cache
          
          # Remplacer l'ancien
          cd ..
          rm -rf old_current
          if [ -d "current" ]; then
            mv current old_current
          fi
          mv temp_deploy current
          
          # Symlink vers public
          rm -f index.php .htaccess
          ln -s current/public/index.php index.php
          ln -s current/public/.htaccess .htaccess